#pragma once
#define CONFIG_USER_H

#ifdef RGBLIGHT_ENABLE
  #define RGBLIGHT_SLEEP

  #ifndef RGBLIGHT_ANIMATIONS
    #define RGBLIGHT_ANIMATIONS
  #endif

  #undef RGBLIGHT_SAT_STEP
  #define RGBLIGHT_SAT_STEP 12

  #define RGBLIGHT_EFFECT_BREATHING
  #define RGBLIGHT_EFFECT_RAINBOW_MOOD
  #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
  #define RGBLIGHT_EFFECT_SNAKE
  #define RGBLIGHT_EFFECT_KNIGHT
  #define RGBLIGHT_EFFECT_CHRISTMAS
  #define RGBLIGHT_EFFECT_STATIC_GRADIENT
  #define RGBLIGHT_EFFECT_RGB_TEST
  #define RGBLIGHT_EFFECT_ALTERNATING
#endif

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2
