AUTO_SHIFT_ENABLE = yes

NO_AUTO_SHIFT_SPECIAL = yes
NO_AUTO_SHIFT_NUMERIC = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_ANIMATION = yes

LEADER_ENABLE = yes

BOOTMAGIC_ENABLE = yes
COMMAND_ENABLE = no
KEYLOGGER_ENABLE = no

TAP_DANCE_ENABLE = no

